### ISSUE TITLE
The intercom adapter does not load the Intercom API correctly

### ISSUE THREAD

**Issue by Artmann** [poteto/ember-metrics#109]
The intercom adapter does not always load the Intercom API correctly as it's dependent on window.load.

**Comment by wecc** [comment]
At the end of [this line](https://github.com/poteto/ember-metrics/blob/master/addon/metrics-adapters/intercom.js#L33) the Intercom JS snippet depends on window `load`/`onload`. However, when the adapter is initialized this event has already been triggered.

We should be able to replace that `if` block with a single call to `l()`.
