### ISSUE TITLE
I've created an adapter addon for Chameleon

### ISSUE THREAD

**Issue by cibernox** [poteto/ember-metrics#117]
I've just created today this addon: https://github.com/cibernox/ember-metrics-chameleon-adapter

It's basically code that I wrote ~6m ago, but now I happen to need in two projects and I decided to extract it into an addon.

[Chameleon](https://www.trychameleon.com/) is not exactly a tracking library, but the similarities are enough to make ember-metrics somehow useful and a good abstraction around any library that that you want to lazy-initialize from an external script to then identify/trackEvents with it.

If you even want to merge this adapter into the default set of adapter just let me know and I'll be happy to PR those changes here.

**Comment by poteto** [comment]
Thanks for this! I think it's actually best for it to be separate. I want to extract all the different adapters to separate addons anyway
