### ISSUE TITLE
Consider Integrating Analytics.js

### ISSUE THREAD

**Issue by blatyo** [poteto/ember-metrics#16]
[Analytics.js](https://github.com/segmentio/analytics.js) has a ton of existing integrations with a bunch of different providers. Figured I'd mention it since your project has a similar goal.

Cheers

**Comment by devinrhode2** [comment]
QUESTION: does ember-metrics use the analytics.js library from Google Analytics? https://developers.google.com/analytics/devguides/collection/analyticsjs/

I think the one you linked to from segment.io is a great library for ember-metrics to delegate a lot of work to.

**Comment by blatyo** [comment]
There is both
