### ISSUE TITLE
Is `activate` the right place to call `trackPage`?

### ISSUE THREAD

**Issue by geoffreyd** [poteto/ember-metrics#19]
> Due to the way Single Page Applications implement routing, you will need to call this on the activate hook of each route to track all page views.

Is `activate` really the best place to call this? what if I'm moving between pages on the same route (i.e. multiple products). activate only runs the first time the route is entered, and not between model changes.

Should the Docs instead suggest this be be called in a `didTransition` action?

**Comment by gwlortscher** [comment]
Agree, `didTransition` is simple, appears to work great and is also the approach suggested in the Ember cookbooks: http://guides.emberjs.com/v1.13.0/cookbook/helpers_and_components/adding_google_analytics_tracking/

**Comment by poteto** [comment]
:+1: I'll update the readme
