### ISSUE TITLE
Can't seem to use invoke

### ISSUE THREAD

**Issue by rstudner** [poteto/ember-metrics#210]
So I extended the built in Mixpanel adapter (just to override 1 method, nothing big) but when I do invoke I get this error:

```
TypeError: t[e] is not a function
    at index.js:133
    at Array.forEach (<anonymous>)
    at o.invoke (index.js:133)
    at login.js:104
```

from the line of code:
```
          get(this, 'metrics').invoke('opt_out_tracking', 'ExpelMixpanel', {});
```

If I literally just get the service, raw, for ember inspector and do $E.invoke() I get the same error

**Comment by rstudner** [comment]
Unminified error seems to be:
```
metrics.js:135 Uncaught TypeError: adapter[methodName] is not a function
    at selectedAdapterNames.map.forEach.adapter (metrics.js:135)
    at Array.forEach (<anonymous>)
    at Class.invoke (metrics.js:135)
    at <anonymous>:1:4
```

**Comment by livfwd** [comment]
@rstudner I'm running into this exact thing. Would you mind sharing your solution?

**Comment by monsha** [comment]
@rstudner I run into the same error, what was the error?

**Comment by livfwd** [comment]
@monsha we ran into this too. The issue for us was that we were missing the fact that the second argument to #invoke is optional.

`invoke(method, [analyticsName], options)`

**Comment by monsha** [comment]
thanks @livfwd, I tried it with/without second arg and nothing. The problem was that the adapter didn't have the function implemented

**Comment by rstudner** [comment]
Yeah, the entire function was simply missing / should have been caught by tests.
