### ISSUE TITLE
GDPR Compliance - IP Anonymisation

### ISSUE THREAD

**Issue by Redsandro** [poteto/ember-metrics#219]
In order to comply with European GDPR law, we need to anonymize tracking data.

[Google suggests](https://developers.google.com/analytics/devguides/collection/gtagjs/ip-anonymization) to enable it with this simple boolean:

```js
gtag('config', '<GA_TRACKING_ID>', { 'anonymize_ip': true })
```

Or with the (happy 10 year anniversary) old  `ga` API use this [config parameter](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#anonymizeIp):

```js
ga('set', 'anonymizeIp', true)
```

Is this possible to set in `ember-metrics`? If not, we should figure out a way to set this, as this is a requirement if we want to use `ember-metrics` in Europe.

**Comment by Alexander-N** [comment]
You can simply add `anonymizeIp: true` to the config. See https://fullstackstanley.com/read/configuring-ember-js-analytics-for-gdpr for an example.

**Comment by Redsandro** [comment]
Seems simple enough. Somehow I had missed that. Thank you @Alexander-N
