### ISSUE TITLE
Proposal: expose metrics.context for properties that should be included with every event

### ISSUE THREAD

**Issue by opsb** [poteto/ember-metrics#35]
Most apps have certain pieces of context that should be included with every pageView or event e.g. currentUser.name, currentTenant.name.

I'd like to propose that we expose `metrics.context`. Anything that's bound to this context would be merged into the options e.g.

    export default Ember.Route.extend({
        setupController(controller, model) {
            var currentTenant = model;
            this.set('metrics.context.tenantName', currentTenant.name);
        }
    });

    metrics.trackEvent({event: 'demo_requested'}); 
    // => {event: 'demo_requested', tenantName: "name of current tenant"};

I'm currently adding it to an app by wrapping the metrics service with another analytics service that does the same thing but it occurred to me that it might be a useful feature to include in the library. If people are keen I'll put a PR together.

**Comment by poteto** [comment]
I will gladly accept a PR for this, I had a similar idea I wanted to implement. Thanks!

**Comment by opsb** [comment]
Ok, great, it should be next couple of days.
