### ISSUE TITLE
More integrations 

### ISSUE THREAD

**Issue by elwayman02** [poteto/ember-metrics#38]
On my phone, so I can't flesh this out, but I figured I'd leave this link here as a list of possible integrations to add, as people need them and/or want to contribute something. Several are already supported or WIP, yay! 

http://www.practicalecommerce.com/articles/74832-14-Alternatives-to-Google-Analytics

**Comment by elwayman02** [comment]
Keeping #24 in mind as a way to keep the build size low even with all the adapters included in the addon

**Comment by jasonmit** [comment]
@elwayman02 I just closed on #24 if you want to work on more integrations

**Comment by elwayman02** [comment]
:+1:
