### ISSUE TITLE
Depreciation in Ember 2.1

### ISSUE THREAD

**Issue by ryanjm** [poteto/ember-metrics#48]
In 2.1 a deprecation was added:

> DEPRECATION: The `initialize` method for Application initializer 'metrics' should take only one argument - `App`, an instance of an `Application`. [deprecation id: ember-application.app-initializer-initialize-arguments] See http://emberjs.com/deprecations/v2.x/#toc_initializer-arity for more details.

If I get a chance later, I'll try to create a PR to fix this. But if someone else has time to do it sooner, that'd be great.

**Comment by poteto** [comment]
Thanks for reporting! It's a simple fix, I have done it for my other addons and overlooked this one.
