### ISSUE TITLE
Support for Piwik

### ISSUE THREAD

**Issue by halfdan** [poteto/ember-metrics#58]
I would be very interested in contributing tracking for [Piwik](https://piwik.org). Would that be something you are interested in?

**Comment by poteto** [comment]
Sure, I'd be happy to accept a PR!

**Comment by Kaceykaso** [comment]
+1 to this! Using Piwik now, tried to make my own service, but calls seem to be getting dropped somewhere. Would be happy to help on this effort :)

**Comment by sly7-7** [comment]
We have the same need, I begin to work on an adapter inside my app, and will make a PR when I have something working
