### ISSUE TITLE
Not recognizing passed in services

### ISSUE THREAD

**Issue by gnazarkin** [poteto/ember-metrics#59]
I'm having issues specifying the specific services I want to use. Not sure what the correct syntax is but I've tried all combinations specified in the readme. An example of what I've tried:
```
this.get('metrics').trackEvent(['Mixpanel', 'Segment'], { event: "Event example" });
```

**Comment by poteto** [comment]
Currently the API only supports specifying a single service:

```js
this.get('metrics').trackEvent('Mixpanel', { event: "Event example" });
```

Which is a little annoying, but I will look into adding a feature which lets you specify multiple services using the same call
