### ISSUE TITLE
Accessing adapter's specific API

### ISSUE THREAD

**Issue by sly7-7** [poteto/ember-metrics#66]
Using the Piwik service, I wanted to use its `trackLink(url, linkType)` function.

For now, it's possible, by implementing the trackLink function in the adapter, and calling it via `metrics.invoke('trackLink', 'Piwik', { url: 'url', linkType: 'download' })`

This seems obviously not possible to add each possible adapter function in the metrics api, so I wonder what could be done for such a case.

Maybe using invoke is just fine, and in that case, I will gladly open a PR to document it in the readme.

**Comment by ronco** [comment]
I'm also interested in accessing specific adapter APIs.  In my case I'm interested in setting a custom google analytics [dimension](https://support.google.com/analytics/answer/2709828?hl=en#collection): `window.ga('set', 'dimension1', value);`

Is re-opening the adapter and using `invoke` directly as @sly7-7 suggests the correct way to go about it?

**Comment by poteto** [comment]
I think using `invoke` is fine and should be public API, as you correctly point out that the service cannot possibly implement all methods across different services. I would gladly accept a PR for a README update. Thanks!

**Comment by sly7-7** [comment]
@poteto It's time to sleep now, but I will try to tackle this tomorrow :smile:

**Comment by lolmaus** [comment]
Please share an example of tracking a custom dimension to Google Analytics.

**Comment by queenvictoria** [comment]
@lolmaus and @ronco 

So I think I've done this correctly by extending the GoogleAnalytics adapter and adding a method for setting dimensions.

I tried `metrics.invoke("set", "GoogleAnalytics", "dimension1", "foo");` but I get an error that set expects a string and I passed in an object which I imagine means that metrics is munging the parameters that are passed in before passing it to the underlying `set` method on `ga`.

So...

Create a custom adapter.

```shell
$ ember generate metrics-adapter google-analytics-custom
```

Inherit from the GoogleAnalytics adapter. 
Create a `dimensions` method that expects a dimensions object.

```javascript
import BaseAdapter from 'ember-metrics/metrics-adapters/google-analytics';

export default BaseAdapter.extend({
  toStringExtension() {
    return 'GoogleAnalyticsCustom';
  },

  dimensions(options = {}) {
    if ( window.ga ) {
      Object.keys(options).forEach(function(key) {
        if ( options[key] ) {
          window.ga('set', key, options[key]);
        }
      });
    }
  },
});
```

Change all your references to the `metrics` `GoogleAnalytics` tracker to `GoogleAnalyticsCustom`.

```javascript
// config/environment.js
// ...
    metricsAdapters: [
      {
        name: 'GoogleAnalyticsCustom',
        environments: ['production', 'development'],
        config: {
          id: 'UA-xxxxxxxxx-x,
        }
      }
    ],
// ...
```

Call `metrics` from somewhere sensible.

```javascript
          const options = { dimension1: "foo" , dimension2: "bar" };
          metrics.invoke("dimensions", "GoogleAnalyticsCustom", options);
```
