### ISSUE TITLE
throwing error when in development

### ISSUE THREAD

**Issue by Jordan4jc** [poteto/ember-metrics#67]
When I have the config for mixpanel set to only do it in `production` when I'm in development and come across code that implements `identify` I'm getting an error in the console saying

    Error while processing route: index.index Cannot read property 'identify' of undefined TypeError: Cannot read property 'identify' of undefined

And 

    TypeError: Cannot read property 'identify' of undefined

**Comment by poteto** [comment]
Do you have a full stacktrace?

**Comment by Jordan4jc** [comment]
It appears it's not doing it now, so... I guess I'll close and reopen if it happens again
