### ISSUE TITLE
Use set prior to send?

### ISSUE THREAD

**Issue by typeoneerror** [poteto/ember-metrics#82]
I wonder if in the GA adapter, `set` shouldn't be used to update the tracker prior to `send`. The documentation indicates:

> While technically the send command for pageview hits accepts an optional page field as the third parameter, passing the page field that way is not recommend when tracking single page applications. This is because fields passed via the send command are not set on the tracker—they apply to the current hit only. Not updating the tracker will cause problems if your application sends any non-pageview hits (e.g. events or social interactions), as those hits will be associated with whatever page value the tracker had when it was created.

https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications#tracking_virtual_pageviews

I'm not sure if how the way the adapter currently works (sending object to `send` with `hitType`) will address this, so thought I'd open this issue.

**Comment by jblotus** [comment]
+1
