### ISSUE TITLE
Add support for environments to Google Tag Manager adapter

### ISSUE THREAD

**Issue by ronco** [poteto/ember-metrics#84]
Google Tag Manager has support for different [environments](https://support.google.com/tagmanager/answer/6311518?hl=en).  This could be useful for publishing different versions of containers to production vs a staging environment.  In order to consume these different containers there are additional query params on the script tag for gtm.js:
- gtm_auth
- gtm_preview
- gtm_cookies_win

I've implemented a local version of the gtm adapter supporting this, and I'd be happy to PR it to the official adapter if there's interest.

**Comment by briangonzalez** [comment]
@ronco Care to take a stab at this?
