### ISSUE TITLE
Reinitialize Adapters for Different Pods

### ISSUE THREAD

**Issue by tomoguisuru** [poteto/ember-metrics#91]
We have a rather large app with a bunch of different pods under. Right now, I can pass the info in using lazy loading but only the info from the first loaded pod is used. Sounds crazy, right? (We're using Segment for this example)

Why would you do something like that you ask? 

Because it would allow us to treat our pods like separate apps all living under the same umbrella with different and distinct tracking information. I'd really hate to have to split all our code into separate apps just to get the tracking info working as described.

I think it would be awesome if I could use the lazy loading technique to override an adapter instance with a new key when loading into a route. 

Do you have any suggestions on how to accomplish this?

**Comment by briangonzalez** [comment]
@tomoguisuru Are you able to post some sample code?
