### ISSUE TITLE
Example of Google Tag Manager

### ISSUE THREAD

**Issue by netvampire** [poteto/ember-metrics#99]
Could you please provide an example of how to use Google TagManager with the dataLayer property being populated.

It would be really appreciated.

Thank you.

**Comment by lionelrudaz** [comment]
Well, actually, that's pretty simple. You just need to inject the values in the options of your tracking methods. Here's an example where I send an event "searchDisplay" to my services:

```
this.get('metrics').trackEvent({
      'event': 'searchDisplay',
      'adverts': advertIds,
    });
```

Please note that your variable in GTM will have to be prefixed with "event". In my example, to get the value of adverts, in GTM I had to create a dataLayer variable called eventAdverts.

Really straight forward if you dig into the gtm adapter.

Hope this helps.
